// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pyramakerz_Task.Models;

[Table("Grade")]
public partial class Grade
{
    [Key]
    public int Gr_Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateTo { get; set; }

    public int? Section_Id { get; set; }

    [InverseProperty("Grade")]
    public virtual ICollection<Classroom> Classrooms { get; set; } = new List<Classroom>();

    [ForeignKey("Section_Id")]
    [InverseProperty("Grades")]
    public virtual Section Section { get; set; }

    [InverseProperty("Grade")]
    public virtual ICollection<StudentAcademicYear> StudentAcademicYears { get; set; } = new List<StudentAcademicYear>();
}