// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pyramakerz_Task.Models;

[Table("Section")]
public partial class Section
{
    [Key]
    public int Se_Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int? School_Id { get; set; }

    [InverseProperty("Section")]
    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    [ForeignKey("School_Id")]
    [InverseProperty("Sections")]
    public virtual School School { get; set; }
}