// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pyramakerz_Task.Models;

[Table("Classroom")]
public partial class Classroom
{
    [Key]
    [Column("Cl-_Id")]
    public int Cl__Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int? Number { get; set; }

    public int? Academic_Year_Id { get; set; }

    public int? Grade_Id { get; set; }

    [ForeignKey("Academic_Year_Id")]
    [InverseProperty("Classrooms")]
    public virtual Acadimic_Year Academic_Year { get; set; }

    [ForeignKey("Grade_Id")]
    [InverseProperty("Classrooms")]
    public virtual Grade Grade { get; set; }

    [InverseProperty("Class")]
    public virtual ICollection<StudentAcademicYear> StudentAcademicYears { get; set; } = new List<StudentAcademicYear>();
}