// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pyramakerz_Task.Models;

[Table("School")]
public partial class School
{
    [Key]
    public int Sc_Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ReportHeaderOneEn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ReportHeaderOneAr { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ReportHeaderTwoEn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ReportHeaderTwoAr { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ReportImage { get; set; }

    [InverseProperty("School")]
    public virtual ICollection<Acadimic_Year> Acadimic_Years { get; set; } = new List<Acadimic_Year>();

    [InverseProperty("School")]
    public virtual ICollection<Section> Sections { get; set; } = new List<Section>();

    [InverseProperty("School")]
    public virtual ICollection<StudentAcademicYear> StudentAcademicYears { get; set; } = new List<StudentAcademicYear>();
}