// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pyramakerz_Task.Models;

[Table("Semester")]
public partial class Semester
{
    [Key]
    public int Se_Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateTo { get; set; }

    public int? Academic_Year_Id { get; set; }

    [ForeignKey("Academic_Year_Id")]
    [InverseProperty("Semesters")]
    public virtual Acadimic_Year Academic_Year { get; set; }

    [InverseProperty("Semester")]
    public virtual ICollection<StudentAcademicYear> StudentAcademicYears { get; set; } = new List<StudentAcademicYear>();
}