// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pyramakerz_Task.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    public int Std_id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Std_Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Mobile { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Nationality { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Gender { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<StudentAcademicYear> StudentAcademicYears { get; set; } = new List<StudentAcademicYear>();
}