// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pyramakerz_Task.Models;

[Table("StudentAcademicYear")]
public partial class StudentAcademicYear
{
    [Key]
    public int St_Ac_Id { get; set; }

    public int? Student_Id { get; set; }

    public int? School_Id { get; set; }

    public int? Class_Id { get; set; }

    public int? Grade_Id { get; set; }

    public int? Semester_Id { get; set; }

    [ForeignKey("Class_Id")]
    [InverseProperty("StudentAcademicYears")]
    public virtual Classroom Class { get; set; }

    [ForeignKey("Grade_Id")]
    [InverseProperty("StudentAcademicYears")]
    public virtual Grade Grade { get; set; }

    [ForeignKey("School_Id")]
    [InverseProperty("StudentAcademicYears")]
    public virtual School School { get; set; }

    [ForeignKey("Semester_Id")]
    [InverseProperty("StudentAcademicYears")]
    public virtual Semester Semester { get; set; }

    [ForeignKey("Student_Id")]
    [InverseProperty("StudentAcademicYears")]
    public virtual Student Student { get; set; }
}